### ISSUE TITLE
安装后，使用找不到模块

### ISSUE THREAD

**Issue by fengfirst** [jdf2e/nutui-biz#3]
npm i @nutui/nutui-biz

发现dist目录下的结构是这样的
![image](https://user-images.githubusercontent.com/1661545/228290049-830efd93-52bc-4a51-96f6-7c58938801a5.png)

**Comment by yangjinjun3** [comment]
感谢反馈！ 可以先尝试测试版1.0.0-beta.1，稍后我们会发 1.0.1 修复此问题
