### ISSUE TITLE
VUE版本什么时候出来？

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui-biz#6]

**Comment by yangjinjun3** [comment]
目前规划的是先做react，等做vue时会周知大家的

**Comment by beanhacker** [comment]
有个大体的近期计划时间M?因为我之前做的一版系统，现正准备切到VUE3，选咱们的业务组件，替代我个人开发的VUE2旧组件。当然也是旧组件有不少使用问题，个人精力和时间有限，难以精细优化。不晓得开发VUE版本的时间代价有多大？六月前能出一版M?

**Comment by yangjinjun3** [comment]
首先看下下面链接，特色组件也是业务组件，能满足您的需求不，也是Vue3版本的
https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/button

然后，业务组件的Vue版本，部门调整的原因，得看领导规划，敬请谅解～～～
